/** Figma Disciplines 2036:521 — 14 lanes, two per row. Copy verbatim. */
export type Discipline = { n: string; kicker: string; title: string; body: string[]; /** slug of the detail page, when one exists */ page?: string; icon?: "disc01" | "disc02" | "disc03" | "disc04" | "disc05" | "disc06" | "disc07" | "disc08" | "disc09" | "disc10" | "disc11" | "disc12" | "disc13" | "disc14" };
export const DISCIPLINES_PAGE: Discipline[] = [
  { n: "01", kicker: "Electroplating and aqueous electrolytic processes", title: "Electroplating", page: "electroplating", icon: "disc01", body: ["Zinc, nickel, chrome, copper, silver, gold and alloy plating. Rack and barrel processes. Hard chrome on hydraulic rods, rollers and precision components.", "We recruit process engineers, chemists, line supervisors, quality managers and operations leaders across general industrial, aerospace, defence and automotive platers."] },
  { n: "02", kicker: "Aluminium and multi-metal", title: "Anodising & conversion coatings", page: "anodising", icon: "disc02", body: ["Sulphuric, chromic, hard and architectural anodising. Chromate and trivalent conversion coatings, phosphating, passivation.", "We recruit across architectural anodisers, aerospace finishers, specialist hard anodisers and general industrial converters."] },
  { n: "03", kicker: "Powder coating, wet paint and industrial coatings", title: "Powder coating and industrial coatings", page: "powder-coating", icon: "disc03", body: ["Architectural powder coating to Qualicoat and BS EN standards, high-performance industrial coatings, contract finishing and wet paint systems.", "We recruit production managers, quality leads, applicators, BDMs and directors across architectural, industrial and coating equipment manufacturers."] },
  { n: "04", kicker: "Heat treatment and thermochemical diffusion", title: "Heat treatment", page: "heat-treatment", icon: "disc04", body: ["Case hardening, carburising, nitriding, vacuum, atmosphere and induction processes.", "We recruit metallurgists, process engineers, furnace managers and quality professionals across commercial heat treaters and captive in-house facilities."] },
  { n: "05", kicker: "Thermal spray and hardfacing", title: "Thermal spray", page: "thermal-spray", icon: "disc05", body: ["HVOF, plasma, arc and flame spray. Wear, corrosion and dimensional restoration for aerospace, energy, oil and gas.", "We recruit coating engineers, operators, development chemists and commercial leaders across specialist sprayers."] },
  { n: "06", kicker: "PVD, CVD and advanced surface technologies", title: "PVD, CVD and advanced deposition", icon: "disc06", body: ["Thin-film deposition, DLC, tool coatings and next-generation surface engineering.", "We recruit R&D scientists, process engineers, coating chamber specialists and commercial leaders across vacuum and plasma-based surface technology businesses."] },
  { n: "07", kicker: "Electroless plating and autocatalytic processes", title: "Electroless plating", icon: "disc07", body: ["Electroless nickel (EN), electroless copper and autocatalytic deposition for uniform thickness on complex geometries. Used heavily in oil and gas, electronics, automotive and precision engineering.", "We recruit process chemists, line technicians, quality leads and operations managers across specialist EN platers and contract finishers."] },
  { n: "08", kicker: "Galvanising and hot-dip processes", title: "Galvanising", icon: "disc08", body: ["Hot-dip galvanising, spin galvanising and zinc flake coatings for structural steel, fasteners and fabrications.", "We recruit plant operators, production managers, quality engineers and commercial leaders across general galvanisers and specialist fastener coaters."] },
  { n: "09", kicker: "Metal polishing, finishing and deburring", title: "Metal polishing and finishing", icon: "disc09", body: ["Mechanical polishing, vibratory finishing, barrel tumbling, electropolishing and deburring. Used across medical devices, food processing, architectural metalwork and precision components.", "We recruit skilled polishers, finishing supervisors, production managers and technical leads."] },
  { n: "10", kicker: "Industrial cleaning and pre-treatment", title: "Industrial cleaning and pre-treatment", icon: "disc10", body: ["Aqueous cleaning, ultrasonic cleaning, vapour degreasing, pickling and chemical pre-treatment lines. The upstream processes that sit in front of every coating and plating operation.", "We recruit process engineers, line supervisors, EHS specialists and plant managers."] },
  { n: "11", kicker: "Blasting, shot peening and surface preparation", title: "Blasting and shot peening", icon: "disc11", body: ["Shot, grit and bead blasting, automated shot peening and controlled surface profiling for fatigue life improvement. Aerospace, automotive and energy applications.", "We recruit operators, Almen technicians, process engineers and quality professionals."] },
  { n: "12", kicker: "PCB finishing, etching and electronics plating", title: "PCB and electronics finishing", icon: "disc12", body: ["Copper plating, ENIG, HASL, immersion tin and gold for printed circuit boards. Chemical etching and photochemical machining for precision metal parts.", "We recruit process engineers, chemists, production managers and quality leads across PCB manufacturers and contract etchers."] },
  { n: "13", kicker: "Weld overlay, cladding and laser surface treatment", title: "Weld overlay and surface cladding", icon: "disc13", body: ["MIG, TIG and submerged arc weld overlay. Laser cladding, laser hardening and directed energy deposition for wear and corrosion protection.", "We recruit welding engineers, laser process specialists, metallurgists and project managers across energy, nuclear and heavy industry contractors."] },
  { n: "14", kicker: "Plating on plastics and composite finishing", title: "Plating on plastics", icon: "disc14", body: ["Decorative and functional plating on ABS, PC/ABS and composite substrates for automotive, consumer electronics and bathroom fittings.", "We recruit process engineers, chemists, tooling specialists and production managers across PoP specialists and automotive Tier 1 finishers."] },
];
